name = "SampleChains"
uuid = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
