name = "SampleChains"
uuid = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ConcreteStructs = "0.2"
NestedTuples = "0.1"
StatsBase = "0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
